### PR TITLE
Major Refactor

### PR DESCRIPTION
**Pull request by wolveix**
## Commit Notes
Additional objects implemented
Standardized function naming
Fixed missing error handling
Support and enforce QB's rate limiting
Bumped Go to 1.18 as 1.14 is EOL
Ran `gofumpt -w` over the repo to cleanup code formatting

## Description
Hey! Awesome library, the authorization flow was something I was struggling with myself, so this saved me a lot of time.

I've refactored the majority of the library to try and enforce consistency throughout. I've also implemented a few new entities. I realise this is a pretty significant refactor, and I'm sure you'll question or disagree with certain decisions made. But please take a look when you have the time to do so, and I'll be sure to either explain or resolve any issues you raise.

Thanks!

### CODE REVIEW

**Comment by wolveix** [comment]
@rwestlund is there any chance of this getting reviewed? :)

**Comment by rwestlund** [comment]
Hey, sorry for not looking at this sooner. It became one of those critical dependencies that gets ignored because it was working.

Looks like there was a build failure: `Error: ../../../go/pkg/mod/golang.org/x/oauth2@v0.19.0/internal/token.go:140:10: lc.v.CompareAndSwap undefined (type atomic.Value has no field or method CompareAndSwap)`

I've tagged current master as v1.0.0 and would be happy to merge this once that's resolved and tag it v2.0.0.

**Comment by wolveix** [comment]
Hey @rwestlund, any chance you've got some time to review this? :)

**Comment by rwestlund** [comment]
Thanks for the follow up. I've merged and tagged v2.0.0!

**Comment by danawoodman** [comment]
Heads up v2.0.0 is not installable afaik:

image

image

image

**Pull request merged**
